name: Generate beIN EPG

on:
  schedule:
    - cron: "0 */6 * * *"   # يشغّل كل 6 ساعات
  workflow_dispatch:
  push:
    paths:
      - 'epg_mapped.xml'   # يشغّل تلقائيًا عند تحديث epg_mapped.xml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch script
      run: bash fetch_bein_epg.sh

    # اعتماد كامل على الملف الأصلي
    - name: Prepare final file
      run: cp epg_mapped.xml epg_mapped_with_logos.xml

    - name: Upload result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bein-epg
        path: epg_mapped_with_logos.xml

    - name: Push updated EPG to repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add epg_mapped_with_logos.xml
        git commit -m "Update EPG [skip ci]" || echo "No changes"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
