name: Translate EPG to Arabic

on:
  push:
    paths:
      - "epg_mapped_with_logos.xml"   # يشتغل فقط لو الملف هذا اتغير
  schedule:
    - cron: "0 0 * * *"   # يشتغل يومياً الساعة 00:00 UTC

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install deep-translator

      - name: Run translation script
        run: |
          python translate_epg.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add epg_mapped_with_logos_ar.xml
          git commit -m "Auto-translated EPG to Arabic" || echo "No changes to commit"
          git push
